name: lint, analyze, and test
on: push
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          sudo apt-get install portaudio19-dev
          python -m pip install --upgrade black
          python -m pip install --upgrade pylint
          python -m pip install --upgrade mypy
          python -m pip install --upgrade -r tests/tests_requirements.txt
          python -m pip install --upgrade tox
      - name: Check formatting with Black
        run: |
          black --check --diff src tests
      - name: Install glyphtune
        run: |
          pip install .
      - name: Lint with Pylint
        run: |
          pylint src tests
      - name: Analyze with mypy
        run: |
          mypy src tests
      - name: Test with tox
        run: |
          tox
